### ISSUE TITLE
Re-factor models module

### ISSUE THREAD

**Issue by skasberger** [gdcc/pyDataverse#102]
Re-factor the models module. Goal is to integrate it better with other tools and pyDataverse modules and to extend the functionality to make the usage seamless.

## Prepare

* [ ] #97 
* [ ] #98 
* [ ] #48 
* [ ] Collect mappings
* [ ] Collect schemas
* [ ] Collect use-cases
* [ ] Collect integrations
  * [ ] Pandas #97 
  * [ ] API module with models module #98 
* [ ] Define process of mapping and schema creation
  * [ ] think it with use-cases in mind
  * [ ] think it with mappings in mind
  * [ ] think it with integrations in mind
* [ ] Define mapping data-structures
  * [ ] https://stackoverflow.com/questions/50041661/bidirectional-data-structure-conversion-in-python
  * [ ] CSV
  * [ ] JSON
    * [ ] Dataverse Upload JSON default
    * [ ] Dataverse Download JSON default
    * [ ] DSpace
  * [ ] XML
    * [ ] DDI 
* [ ] Define schema data-structure
  * [ ] required, data type, unique, limits, formats (email, date), minItems
  * [ ] `controlledVocabulary`: subject, authorIdentifierScheme, contributorType, country, journalArticleType, language, publicationIDType
  * [ ] CSV
  * [ ] JSON
    * [ ] Dataverse Upload JSON default
    * [ ] Dataverse Download JSON default
    * [ ] DSpace
  * [ ] XML
    * [ ] DDI 
* [ ] Research tools
  * [ ] pydantic
  * [ ] `main.create_model()`
  * [ ] https://github.com/koxudaxi/datamodel-code-generator
  * [ ] pydantic_sqlalchemy
    * [ ] `sqlalchemy_to_pydantic`
  * [ ] Idea: For JSON, get pydantic data model from JSON schema file. get mapping from json file. key is the location of source variable, value the name of the pyDataverse attribute.
  * [ ] Idea: For CSV, get pydantic data model from csv header row and type row. get mapping from json file. key is the name of the source variable, value the name of the pyDataverse attribute.
  * [ ] offer dataverse default schemas which are used from Dataverse by default. `DataverseDefault()`, `DatasetDefault()`, `DatafileDefault()`
  * [ ] use pydantic models with validators for internal data structure https://pydantic-docs.helpmanual.io/usage/models/
    * [ ] Validate incoming data dicts
    * [ ] Export data with .dict() and .json()
  * [ ] JSON Schema erstellen mit pydantic: https://pydantic-docs.helpmanual.io/usage/schema/#schema-customization
* [ ] jsonpath https://pypi.org/project/jsonpath-ng/

## Implementation

* [ ] Write tests
* [ ] Update code
  * [ ] Create base class (ABC or normal), called `BaseModel()`
  * [ ] Implement Dataverse Upload JSON mappings and schemas
  * [ ] Implement Dataverse Download JSON mappings and schemas
  * [ ] Prototype: CSV templates mappings and schemas
  * [ ] Prototype: DSpace mappings and schemas
  * [ ] Prototype: DDI XML mappings and schemas
* [ ] Update Docs
* [ ] Update Docstrings
* [ ] Run pytest
* [ ] Run tox
* [ ] Run pylint
* [ ] Run mypy

## Review

* [ ] Code
* [ ] Tests
* [ ] Docs

## Follow-Ups

* [ ] Implement CSV mapping
* [ ] Implement Dataverse Upload JSON mapping
* [ ] Implement Dataverse Download JSON mapping #16 
* [ ] Implement DSpace mapping #47 
* [ ] Implement DDI XML mapping #18

**Comment by JR-1991** [comment]
Just discovered this issue and the idea seems to align very well to what has been done with [EasyDataverse](https://github.com/gdcc/easyDataverse) already. The library also utilizes PyDantic and generates objects according to the metadatablock schemes found at `api/metadatablocks/blockname`.

Wouldnt it make sense to merge the functionality into PyDataverse? In my opinion having a single Python library makes more sense since both are heading in the same direction. What do you think @skasberger @pdurbin @poikilotherm?

**Comment by pdurbin** [comment]
I think a single library would be easier for the community, sure.

**Comment by skasberger** [comment]
Agree on that, especially as  pyDataverse is very lightweight and is made to build upon other, more specialized services/functions.
